FROM node:16-alpine as builder

WORKDIR /app
COPY ./package.json ./
RUN npm i --force

ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL

COPY ./ ./
RUN npm run build
CMD ["npm", "run", "start"]
EXPOSE 3000


FROM caddy:2.5.2-alpine
COPY --from=builder /app/build /srv/app