FROM node:16-alpine AS builder

# WORKDIR /app
# COPY ./package.json ./
# RUN npm i --force

ARG REACT_APP_URL
ENV REACT_APP_URL=$REACT_APP_URL



WORKDIR /app
COPY ./package.json ./
RUN npm i --force
COPY . .
CMD ["npm", "run", "start"]


#RUN npm run build
